django-onlineshop/cart/urls.py
from django.urls import path
from . import views
app_name='cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

django-onlineshop/shop/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
# De su dung namespace
app_name = 'shop'

urlpatterns = [
    path('',views.product_list, name='product_list'),
    path('<slug:category_slug>/', views.product_list, name='product_list_by_category'),
    path('<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django-onlineshop/shop/models.py
from django.db import models
from django.urls import reverse
# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, unique=True)

    class Meta:
        ordering = ['name']
        indexes = [
            models.Index(fields=['name'])
        ]
        verbose_name = 'category'
        verbose_name_plural = 'categories'
    
    def get_absolute_url(self):
        return reverse("shop:product_list_by_category", args=[self.slug])
    

    def __str__(self) -> str:
        return self.name


class Product(models.Model):
    # Quan he Category - Products la 1-N (one-to-many): Mot category co nhieu products
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200)
    image = models.ImageField(upload_to='products/%Y/%m/%d/', blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['name']
        indexes = [
            # models.Index(fields=['id, slug']),
            models.Index(fields=['name']),
            models.Index(fields=['-created'])
        ]

    def get_absolute_url(self):
        return reverse("shop:product_detail", args=[self.id, self.slug])
    
    def __str__(self) -> str:
        return self.name

django-onlineshop/shop/views.py
from unicodedata import category
from django.shortcuts import render, get_object_or_404
from .models import Product, Category
from cart.forms import CartAddProductForm
from .recommender import Recommender
# Create your views here.


def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)

    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = Product.objects.filter(category=category)

    return render(
        request,
        "shop/product/list.html",
        {"category": category, "categories": categories, "products": products},
    )

def product_detail(request, id, slug):
    product = get_object_or_404(Product, id=id,slug=slug, available=True)
    cart_product_form = CartAddProductForm()
    r = Recommender()
    recommended_products = r.suggest_products_for([product], 4)
    return render(request, 'shop/product/detail.html', {'product': product, 'cart_product_form': cart_product_form, 'recommended_products': recommended_products})

django-onlineshop/shop/templates/shop/base.html
{% load i18n %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} {% trans "My Shop" %} {% endblock title %}</title>
    <link href="{% static 'css/base.css' %}" rel="stylesheet" />
</head>
<body>
    <div id="header">
        <a href="/" class="logo">{% trans "My shop" %}</a>
                {% get_current_language as LANGUAGE_CODE %}
                {% get_available_languages as LANGUAGES %}
                {% get_language_info_list for LANGUAGES as languages %}
            <div class="languages">
                <p>{% trans "Language" %}:</p>
                <ul class="languages">
                {% for language in languages %}
                <li>
                <a href="/{{ language.code }}/"
                {% if language.code == LANGUAGE_CODE %} class="selected"{% endif %}>
                {{ language.name_local }}
                </a>
                </li>
                {% endfor %}
                </ul>
            </div>
    </div>
    <div id="subheader">
        <div class="cart">
            {% with total_items=cart|length  %}
                {% if total_items > 0 %}
                    {% trans "Your cart:" %}
                    <a href="{% url 'cart:cart_detail' %}">
                        {% blocktrans with total=cart.get_total_price count items=total_items %}
                        
                        {{ items }} item, {{ total}}
                        {% plural %}
                        {{ items }} items, {{ total}}
                        {% endblocktrans %}
                    </a>
                    {% elif not order %}
                    {% trans "Your cart is empty" %}
                {% endif %}
            {% endwith %}
        </div>
    </div>
    <div id="content">
        {% block content %}
        {% endblock content %}
    </div>
</body>
</html>