django-onlineshop/cart/urls.py
from django.urls import path
from . import views
app_name='cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

django-onlineshop/payment/urls.py
from django.urls import path

from . import views
from . import webhooks

app_name='payment'

urlpatterns = [
    path('process/', views.payment_process, name='process'),
    path('completed/', views.payment_completed, name='completed'),
    path('canceled/', views.payment_canceled, name='canceled'),
    path('webhook/', webhooks.stripe_webhook, name='stripe-webhook')
]

django-onlineshop/payment/models.py
from django.db import models

# Create your models here.

django-onlineshop/payment/views.py
from decimal import Decimal
import stripe
from django.conf import settings
from django.shortcuts import render, redirect, reverse, get_object_or_404
from orders.models import Order

stripe.api_key = settings.STRIPE_SECRET_KEY
stripe.api_version = settings.STRIPE_API_VERSION

# Content from chapter 9, page 397
def payment_process(request):
    # The current Order object is retrieved from the database using the order_id session key, which
    # was stored previously in the session by the order_create view.
    order_id = request.session.get("order_id", None)
    order = get_object_or_404(Order, id=order_id)

    if request.method == "POST":
        success_url = request.build_absolute_uri(reverse("payment:completed"))
        cancel_url = request.build_absolute_uri(reverse("payment:canceled"))

        # Stripe checkout session data
        #Stripe checkout session is created with stripe.checkout.Session.create() using the following parameters:
        session_data = {
            "mode": "payment",
            "client_reference_id": order.id,
            "success_url": success_url,
            "cancel_url": cancel_url,
            "line_items": [],
        }


        # add order itmes to the stripe checkout session
        for item in order.items.all():
            session_data['line_items'].append({
                'price_data': {
                    'unit_amount': int(item.price * Decimal('100')),
                    'currency': 'usd',
                    'product_data': {
                        'name': item.product.name
                    }
                },
                'quantity': item.quantity
            })
        
        # Chapter 10 - Page 461 - Add coupon deduce to order payment
        if order.coupon:
            stripe_coupon = stripe.Coupon.create(name=order.coupon.code, percent_off=order.discount, duration="once")
            session_data['discounts'] = [{'coupon': stripe_coupon.id}]
        # Create stripe checkout session
        session = stripe.checkout.Session.create(**session_data)

        # Redirect to Stripe payment form
        '''
        After creating the checkout session, an HTTP redirect with status code 303 is returned to redirect the user to Stripe. The status code 303 is recommended to redirect web applications to 
        a new URI after an HTTP POST has been performed.
        '''

        return redirect(session.url, code=303)
    else:
        """
        If the view is loaded with a GET request, the template payment/process.html is rendered and
        returned. This template will include the order summary and a button to proceed with the
        payment, which will generate a POST request to the view.
        """
        return render(request, "payment/process.html", locals())

#Chapter 9, page 399
def payment_completed(request):
    return render(request, 'payment/completed.html')

def payment_canceled(request):
    return render(request, 'payment/canceled.html')

django-onlineshop/payment/templates/payment/canceled.html
{% extends 'shop/base.html' %}
{% load static %}

{% block title %}
    Payment canceled
{% endblock title %}

{% block content %}
    <h1>Your payment has not been processed</h1>
    <p>There was a problem processing your payment.</p>
    
{% endblock content %}

django-onlineshop/payment/templates/payment/completed.html
{% extends 'shop/base.html' %}
{% load static %}

{% block title %}
    Payment sucessful
{% endblock title %}

{% block content %}
    <h1>Your payment was sucessful</h1>
    <p>Your payment has been processed successfully</p>
    
{% endblock content %}

django-onlineshop/payment/templates/payment/process.html
{% extends 'shop/base.html' %}
{% load static %}

{% block title %}
    Pay your order
{% endblock title %}

{% block content %}
    <h1>Order summary</h1>
    <table class='cart'>
        <thead>
            <tr>
                <th>Image</th>
                <th>Product</th>
                <th>Price</th>
                <th>Quantity</th>
                <th>Total</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            {% for item in order.items.all %}
                <tr class="row {% cycle "1" "2" %}">
                    <td>
                        <img src="{% if item.product.image %}
                            {{ item.product.image.url}}
                            {% else %}
                            {% static 'img/no_image.png' %}
                        {% endif %}" alt="{{ item.product.name }}">
                    </td>
                    <td>{{ item.product.name}}</td>
                    <td class="num"> ${{ item.price }} </td>
                    <td class="num"> {{ item.quantity }}</td>
                    <td class="num"> ${{ item.get_cost }}</td>
                    <td></td>
                </tr>
            {% endfor %}
            {% if order.coupon %}
                <tr class="subtotal">
                    <td>Subtotal</td>
                    <td colspan="3"></td>
                    <td class="num">
                        ${{ order.get_total_cost_before_discount|floatformat:2}}
                    </td>
                </tr>
                <tr>
                    <td>
                        " {{ order.coupon.code }}" coupon
                        {{ order.discount }}% off
                    </td>
                    <td colspan="3"></td>
                    <td class="num neg">
                        -${{ order.get_discount|floatformat:2}}
                    </td>
                </tr>
            {% endif %}
            
            <td class="total">
                <td colspan="4">Total</td>
                <td colspan="3"></td>
                <td class="num"> ${{ order.get_total_cost|floatformat:2 }} </td>
            </td>
        </tbody>
        <form action="{% url 'payment:process' %}" method="POST">
            <input type="submit" value="Pay now">
            {% csrf_token %}
        </form>
    </table>
{% endblock content %}